version: '2'
services:
  jhlibrarymonosess-app:
    image: jhlibrarymonosess
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://jhlibrarymonosess-mysql:3306/jhlibrarymonosess?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  jhlibrarymonosess-mysql:
    extends:
      file: mysql.yml
      service: jhlibrarymonosess-mysql
